version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - busc
  - comput
  - ekoru
  - Ekoru
  - fulltext
  - laptap
  - nestjs
  - nvidia
  - pgvector
  - plainto
  - sáéíóúñü
  - sess
  - setex
  - spanish
  - trgm
  - tsquery
  - tsvector
  - upcycled
ignoreWords: []
import: []
